apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: container-security-mutating
  labels:
    app: container-security
webhooks:
- name: security-mutating.container-security.svc
  clientConfig:
    service:
      name: admission-webhook
      namespace: container-security
      path: /mutate
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
